### ISSUE TITLE
Metrics CSV Grafana

### ISSUE THREAD

**Issue by joaoandrefaria** [SmartBlug/grafana-csv-datasource#2]
Hello,
I'm getting this error when I'm selecting in Metrics some value.

[2018-06-11 10:50:28,386] ERROR in app: Exception on /teste/query [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/var/lib/grafana/plugins/grafana-csv-datasource/backend/PythonServer.py", line 212, in query_metrics
    with open(path+str(folder)+"/"+source+".csv",'rb') as csvfile:
IOError: [Errno 2] No such file or directory: u'/var/lib/grafana/plugins/grafana-csv-datasource/backend/teste/f1.csv'
192.168.150.168 - - [11/Jun/2018 10:50:28] "POST /teste/query HTTP/1.1" 500 -
192.168.150.168 - - [11/Jun/2018 10:50:28] "POST /teste/sources HTTP/1.1" 200 -
192.168.150.168 - - [11/Jun/2018 10:50:28] "OPTIONS /teste/search HTTP/1.1" 200 -
[2018-06-11 10:50:28,411] ERROR in app: Exception on /teste/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/var/lib/grafana/plugins/grafana-csv-datasource/backend/PythonServer.py", line 77, in find_metrics
    with open(path+str(folder)+"/"+source+".csv",'rb') as csvfile:

Can you help please?

**Comment by SmartBlug** [comment]
The error explain that your csv file (/var/lib/grafana/plugins/grafana-csv-datasource/backend/teste/f1.csv) is not available.
Does this file exist? 
If this file exist, have you check if everyone can acces the file according to the access right ?

**Comment by joaoandrefaria** [comment]
Hello,
When I'm adding the datasource it works without any errors.
![screen1](https://user-images.githubusercontent.com/40164154/41277657-c003801c-6e1f-11e8-8892-f63545d9c15f.PNG)
When editing a panel, in metrics when I select a metric, it gives me that error in console.
![screen2](https://user-images.githubusercontent.com/40164154/41277658-c022a244-6e1f-11e8-8857-8357e683fac7.PNG)
![screen4](https://user-images.githubusercontent.com/40164154/41286111-3fd271ac-6e36-11e8-910c-d0aa0b9023e4.PNG)
File is in the paste selected, with permission 644, so it's possible to read.
![screen3](https://user-images.githubusercontent.com/40164154/41277659-c03fe1f6-6e1f-11e8-861a-0de66c642314.PNG)

Thanks if you can help

**Comment by joaoandrefaria** [comment]
It's okay, thanks for the plugin. I got it. Love you
