### ISSUE TITLE
Expected CSV Format

### ISSUE THREAD

**Issue by cluffja** [SmartBlug/grafana-csv-datasource#3]
Hello,

Is there an expected CSV format? I have a CSV with a single column of numbers and a single column of timestamps. Do I need headers? Do I need timestamps in a certain format? My current Python Server error is:

ERROR in app: Exception on /csv/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "PythonServer.py", line 78, in find_metrics
    dialect = csv.Sniffer().sniff(csvfile.read(1024))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 182, in sniff
    self._guess_quote_and_delimiter(sample, delimiters)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 223, in _guess_quote_and_delimiter
    matches = regexp.findall(data)
TypeError: cannot use a string pattern on a bytes-like object

Thanks for the help!

**Comment by cluffja** [comment]
This may be a Python 3.7 issue as it seems your plugin was written for 2.7 or similar.

**Comment by cluffja** [comment]
I had to change print functions and csv.reader.next()

**Comment by cluffja** [comment]
I resolved the issues. It was indeed all issues related to the differences between Python 2.7 and Python 3. In case others come along down the road some print functions, csv.reader.next functions, and zip objects were changed. The zip objects just needed to be wrapped in a list. There may be other bugs but I haven't found them yet.

Additionally, to answer my question specifically about CSV file format: it seems that the first column needs to be timestamp and the subsequent need to be data. Headers are expected.

**Comment by JuanJoseRodriguezMenendez** [comment]
Could you write an example? I'n trying with this simple example 

A,B
1536224384,1
1536224384,0

But I'm getting the values 1 and 0 in the 1970

**Comment by cluffja** [comment]
Here's a snippet of my data:
Time,Data
7/11/18 10:35,1
7/12/18 10:35,2
7/13/18 10:35,3
7/14/18 10:35,4
7/15/18 10:35,5
7/16/18 10:35,6
7/17/18 10:35,7
7/18/18 10:35,8
7/19/18 10:35,9
7/20/18 10:35,10

**Comment by cluffja** [comment]
Again, in theory I think these timestamps that you are using should work. This connector uses the libraries native to dataframes to determine timestamp format. I would expect it to be able to handle Unix timestamps, but I've never tested it.

**Comment by JuanJoseRodriguezMenendez** [comment]
Ok thank you, I have try It and it works.
